# Generated by Django 3.0.7 on 2021-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
