# Generated by Django 3.0.7 on 2021-05-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Coupon'),
        ),
    ]
