# Generated by Django 3.0.7 on 2021-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210515_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
