# Generated by Django 3.0.7 on 2021-05-17 11:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210517_1435'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
