# Generated by Django 3.0.7 on 2021-05-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210519_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
