# Generated by Django 3.0.7 on 2021-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_final_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_order',
            name='status',
            field=models.CharField(choices=[('PREPARED', 'BEING PREPARED'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED'), ('HOLD', 'ON HOLD')], default='PREPARED', max_length=50),
        ),
    ]
