# Generated by Django 3.0.7 on 2021-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20210526_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='item',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
