# Generated by Django 3.0.7 on 2021-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210526_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='item',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
