# Generated by Django 3.0.7 on 2021-05-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20210527_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='item',
        ),
    ]
