# Generated by Django 3.0.7 on 2021-05-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20210527_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('denonym', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
