# Generated by Django 3.0.7 on 2021-05-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_translate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translate',
        ),
    ]
